### ISSUE TITLE
Error while executing(training for Hindi dataset):-  !python train_tacotron.py 

### ISSUE THREAD

**Issue by YoghesWaran** [as-ideas/ForwardTacotron#42]
I have changed the language = 'fr', tts_cleaner_name = 'basic_cleaners' in hparams.py.
The command below gives me no error.
`py preprocess.py --path /content/tacotron/dataset_folder`  

output
```
71 wav files found in "/content/tacotron/dataset_folder."

Using 68 wav files that are indexed in metafile.

+-------------+-----------+--------+------------+-----------+----------------+
| Sample Rate | Bit Depth | Mu Law | Hop Length | CPU Usage | Num Validation |
+-------------+-----------+--------+------------+-----------+----------------+
|    22050    |     9     |  True  |    256     |    1/2    |      200       |
+-------------+-----------+--------+------------+-----------+----------------+
 
████████████████ 68/68 First val sample: 1_1_60`


Completed. Ready to run "python train_tacotron.py" or "python train_wavernn.py". 
```

But when I run 

`python train_tacotron.py` 

I get the following error message:-
```
`Using device: cuda

Initialising Model...

Creating latest checkpoint...
Saving latest weights: /content/tacotron/checkpoints/ljspeech_raw.wavernn/latest_weights.pyt
Saving latest optimizer state: /content/tacotron/checkpoints/ljspeech_raw.wavernn/latest_optim.pyt
2020-12-30 07:09:50.274334: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "train_wavernn.py", line 62, in <module>
    voc_trainer.train(voc_model, optimizer, train_gta=args.gta)
  File "/content/tacotron/trainer/voc_trainer.py", line 46, in train
    path=self.paths.data, batch_size=bs, train_gta=train_gta)
  File "/content/tacotron/utils/dataset.py", line 38, in get_vocoder_datasets
    train_ids, train_lens = zip(*filter_max_len(train_data))
ValueError: not enough values to unpack (expected 2, got 0)`
```

**Comment by AyseEe501** [comment]
> hparams.py'de dili = 'fr', tts_cleaner_name = 'basic_cleaners' olarak değiştirdim. Aşağıdaki komut bana hata vermiyor. `py preprocess.py --path /content/tacotron/dataset_folder`
> 
> çıktı
> 
> ```
> 71 wav files found in "/content/tacotron/dataset_folder."
> 
> Using 68 wav files that are indexed in metafile.
> 
> +-------------+-----------+--------+------------+-----------+----------------+
> | Sample Rate | Bit Depth | Mu Law | Hop Length | CPU Usage | Num Validation |
> +-------------+-----------+--------+------------+-----------+----------------+
> |    22050    |     9     |  True  |    256     |    1/2    |      200       |
> +-------------+-----------+--------+------------+-----------+----------------+
>  
> ████████████████ 68/68 First val sample: 1_1_60`
> 
> 
> Completed. Ready to run "python train_tacotron.py" or "python train_wavernn.py". 
> ```
> 
> Ama koştuğumda
> 
> `python train_tacotron.py`
> 
> Aşağıdaki hata mesajını alıyorum: -
> 
> ```
> `Using device: cuda
> 
> Initialising Model...
> 
> Creating latest checkpoint...
> Saving latest weights: /content/tacotron/checkpoints/ljspeech_raw.wavernn/latest_weights.pyt
> Saving latest optimizer state: /content/tacotron/checkpoints/ljspeech_raw.wavernn/latest_optim.pyt
> 2020-12-30 07:09:50.274334: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
> Traceback (most recent call last):
>   File "train_wavernn.py", line 62, in <module>
>     voc_trainer.train(voc_model, optimizer, train_gta=args.gta)
>   File "/content/tacotron/trainer/voc_trainer.py", line 46, in train
>     path=self.paths.data, batch_size=bs, train_gta=train_gta)
>   File "/content/tacotron/utils/dataset.py", line 38, in get_vocoder_datasets
>     train_ids, train_lens = zip(*filter_max_len(train_data))
> ValueError: not enough values to unpack (expected 2, got 0)`
> ```

I got the same error for train_forward. How did you solve this?

**Comment by riderjensen** [comment]
Has anyone found a solution to this issue?

**Comment by AyseEe501** [comment]
> Bu soruna çözüm bulan var mı?
Unfortunately.I wish I could find it but I couldn't

**Comment by riderjensen** [comment]
I added some extra logging, it seems like a lot of my data is being filtered out due to that `filter_bad_attentions`  function.

```
Using 20 train files. Filtered 3630 files due to bad attention!
Using 0 val files. Filtered 200 files due to bad attention!
```

I am wondering if either my dataset is not large enough or if it has problems. 

`filter_bad_attentions` does a for loop on each item in the dataset and pulls out the name and the mel_len from the array. The items in the array look similar to: `('q-715-audio', 280)`. Then it uses the `attention_score_dict` and selects based on the file name and pulls out the `align_score` and the  `sharp_score`. The items in that dict look like `'q-1019-audio': (0.9242424368858337, 0.3374719023704529)`. At this point we check if `align_score > min_alignment  and sharp_score > min_sharpness` and if that passes, we add it to the returning object. The reason this error occurs is because the returned object is empty and nothing can be pulled out of it. The two values in the if check that we check against are hard coded at https://github.com/as-ideas/ForwardTacotron/blob/master/utils/dataset.py#L139 so I am wondering what makes those correct and if loosening those values is necessary for a smaller dataset. I will keep testing and update on what I find.

**Comment by riderjensen** [comment]
It looks like we can actually change those values in the config.yaml https://github.com/as-ideas/ForwardTacotron/blob/master/config.yaml#L124. You could set it to no filter and bypass this problem though I dont know how that will affect the resulting outcome.
